name: Run fetch_metrics.py daily

on:
  schedule:
    - cron: '59 23 * * *'  # every day at midnight UTC
  workflow_dispatch:      # allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: python token_ai_tracker/fetch_metrics.py